import { StyleSheet, Platform } from 'react-native';

export const createStyles = (theme: any) => StyleSheet.create({
  container: {
    backgroundColor: theme.colors.background,
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 20,
    borderRadius: 6,
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 10,
    color: theme.colors.text,
  },
  imagePicker: {
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderStyle: 'dashed',
    borderRadius: 10,
    padding: 8,
    width: 160,
    height: 160,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  image: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
    borderRadius: 10,
  },
  placeholder: {
    fontSize: 16,
    color: theme.colors.textMuted,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.colors.modalBackdrop,
  },
  modalContent: {
    width: '90%',
    backgroundColor: theme.colors.background,
    padding: 20,
    borderRadius: 10,
    maxHeight: '80%',
  },
  outfitModalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.colors.modalBackdrop,
  },
  outfitModalContent: {
    width: '95%',
    maxHeight: '95%',
    backgroundColor: theme.colors.background,
    padding: 20,
    borderRadius: 15,
    ...theme.shadows.large,
  },
  outfitModalHeader: {
    flexDirection: 'column',
    alignItems: 'center',
    marginBottom: 20,
    paddingTop: Platform.OS === 'ios' ? 50 : 20, // Extra padding for iPhone notch/status bar
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
  },
  outfitModalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: theme.colors.text,
    textAlign: 'center',
    marginBottom: 10,
  },
  weatherInfo: {
    backgroundColor: theme.colors.success + '20',
    padding: 12,
    borderRadius: 12,
    marginBottom: 10,
    alignSelf: 'center',
  },
  weatherText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: theme.colors.success,
    textAlign: 'center',
  },
  closeButton: {
    position: 'absolute',
    top: 15,
    right: 15,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme.colors.surface,
    justifyContent: 'center',
    alignItems: 'center',
    ...theme.shadows.small,
  },
  closeButtonText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: theme.colors.textSecondary,
  },
  imageContainer: {
    height: 350,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.colors.surface,
    borderRadius: 12,
    marginVertical: 15,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  zoomableImage: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  outfitImage: {
    width: '100%',
    height: '100%',
    borderRadius: 10,
  },
  outfitImageTouchable: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  outfitModalControls: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginVertical: 15,
  },
  controlButton: {
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderRadius: 20,
    backgroundColor: theme.colors.primary,
    ...theme.shadows.small,
  },
  controlButtonText: {
    fontSize: 13,
    fontWeight: 'bold',
    color: 'white',
  },
  outfitModalActions: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 20,
    gap: 10,
  },
  actionButton: {
    flex: 1,
    paddingHorizontal: 20,
    paddingVertical: 15,
    borderRadius: 25,
    backgroundColor: theme.colors.primary,
    ...theme.shadows.medium,
    alignItems: 'center',
  },
  actionButtonText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: 'white',
  },
  generateNewButton: {
    backgroundColor: theme.colors.accent,
  },
  keepOutfitButton: {
    backgroundColor: theme.colors.success,
  },
  instructionsContainer: {
    backgroundColor: theme.colors.primary + '15',
    padding: 12,
    borderRadius: 12,
    marginTop: 15,
    borderWidth: 1,
    borderColor: theme.colors.primary + '30',
  },
  instructionsText: {
    fontSize: 13,
    fontWeight: '600',
    color: theme.colors.primary,
    textAlign: 'center',
    lineHeight: 18,
  },
  originalItemsContainer: {
    marginTop: 20,
    padding: 15,
    backgroundColor: theme.colors.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  originalItemsTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 12,
    color: theme.colors.text,
    textAlign: 'center',
  },
  originalItemsScroll: {
    paddingHorizontal: 5,
  },
  originalItemCard: {
    marginRight: 12,
    width: 80,
    height: 80,
    borderRadius: 8,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: theme.colors.primary,
    backgroundColor: theme.colors.card,
    ...theme.shadows.small,
  },
  originalItemImage: {
    width: '100%',
    height: '100%',
  },
  originalItemNumber: {
    position: 'absolute',
    top: 2,
    right: 2,
    fontSize: 10,
    fontWeight: 'bold',
    backgroundColor: theme.colors.primary,
    color: 'white',
    borderRadius: 8,
    paddingHorizontal: 4,
    paddingVertical: 1,
  },
  gearSlotGrid: {
    paddingHorizontal: 16,
    marginTop: 16,
    marginBottom: 20,
  },
  gearRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 16,
    gap: 10,
  },
  gearSlot: {
    width: 110,
    height: 110,
    borderWidth: 2,
    borderColor: theme.colors.border,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.colors.card,
    ...theme.shadows.small,
    position: 'relative',
    paddingVertical: 12,
    paddingHorizontal: 8,
  },
  gearSlotFilled: {
    backgroundColor: theme.mode === 'dark' ? theme.colors.primary + '15' : theme.colors.primary + '08',
    borderColor: theme.colors.primary,
    borderWidth: 2,
  },
  gearSlotImageContainer: {
    width: 65,
    height: 65,
    marginBottom: 8,
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
  },
  gearSlotImage: {
    width: '100%',
    height: '100%',
    borderRadius: 12,
  },
  clearSlotButton: {
    position: 'absolute',
    top: 4,
    right: 4,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: theme.colors.error,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
    ...theme.shadows.small,
  },
  clearSlotText: {
    fontSize: 10,
    fontWeight: 'bold',
    color: 'white',
  },
  gearSlotIcon: {
    width: 42,
    height: 42,
    marginBottom: 8,
  },
  gearSlotLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: theme.colors.textSecondary,
    textAlign: 'center',
    marginTop: 4,
    letterSpacing: 0.3,
  },
  gearSlotLabelFilled: {
    color: theme.colors.primary,
    fontWeight: '700',
  },
  smartSuggestionButton: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 25,
    backgroundColor: theme.colors.accent,
    ...theme.shadows.small,
  },
  smartSuggestionButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  generateOutfitButton: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 25,
    backgroundColor: theme.colors.primary,
    ...theme.shadows.small,
  },
  generateOutfitButtonDisabled: {
    backgroundColor: theme.colors.textMuted,
  },
  generateOutfitButtonText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: 'white',
  },
  generateOutfitButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  generateOutfitIcon: {
    width: 20,
    height: 20,
    marginRight: 8,
  },
  generateOutfitImageButton: {
    width: 350,
    height: 80,
    borderRadius: 16,
    ...theme.shadows.medium,
  },
  equippedCount: {
    fontSize: 12,
    fontWeight: 'bold',
    color: theme.colors.textSecondary,
  },
  slotSelectionModalContent: {
    width: '90%',
    backgroundColor: theme.colors.background,
    padding: 20,
    borderRadius: 10,
    maxHeight: '80%',
  },
  slotSelectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 15,
  },
  slotSelectionTitleContainer: {
    flex: 1,
  },
  slotSelectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 10,
    color: theme.colors.text,
  },
  slotSelectionSubtitle: {
    fontSize: 14,
    color: theme.colors.textSecondary,
  },
  slotSortButton: {
    backgroundColor: theme.colors.surface,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    marginLeft: 10,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  slotSortButtonText: {
    fontSize: 14,
    color: theme.colors.primary,
    fontWeight: '600',
  },
  slotSelectionScroll: {
    maxHeight: '70%',
    marginBottom: 15,
  },
  slotSelectionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    padding: 10,
    backgroundColor: theme.colors.surface,
    borderRadius: 8,
  },
  slotSelectionItemImage: {
    width: 80,
    height: 80,
    borderRadius: 4,
    marginRight: 10,
  },
  slotSelectionItemInfo: {
    flex: 1,
  },
  slotSelectionItemTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 5,
    color: theme.colors.text,
  },
  slotSelectionItemDescription: {
    fontSize: 12,
    color: theme.colors.textSecondary,
  },
  slotSelectionItemTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginVertical: 5,
  },
  slotSelectionItemTag: {
    backgroundColor: theme.colors.border,
    borderRadius: 4,
    padding: 4,
    margin: 2,
  },
  slotSelectionItemTagText: {
    fontSize: 10,
    color: theme.colors.textSecondary,
  },
  slotSelectionCloseButton: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 20,
    backgroundColor: theme.colors.textMuted,
    ...theme.shadows.small,
    alignItems: 'center',
  },
  slotSelectionCloseButtonText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: theme.colors.textSecondary,
  },
  noItemsContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
  },
  noItemsText: {
    fontSize: 16,
    color: theme.colors.textSecondary,
    marginBottom: 5,
  },
  noItemsSubtext: {
    fontSize: 12,
    color: theme.colors.textMuted,
    textAlign: 'center',
  },
  categoryBadge: {
    backgroundColor: theme.colors.success,
    borderRadius: 4,
    padding: 4,
    marginTop: 5,
  },
  categoryBadgeText: {
    fontSize: 10,
    color: 'white',
    fontWeight: 'bold',
  },
  wardrobeInventoryModalContent: {
    width: '90%',
    backgroundColor: theme.colors.background,
    padding: 20,
    borderRadius: 10,
    maxHeight: '80%',
  },
  wardrobeInventoryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 15,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
  },
  wardrobeInventoryTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: 'bold',
    color: theme.colors.text,
  },
  closeInventoryButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme.colors.surface,
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeInventoryButtonText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: theme.colors.textSecondary,
  },
  wardrobeInventoryScroll: {
    maxHeight: '70%',
    marginBottom: 15,
  },
  wardrobeInventoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  wardrobeInventoryItem: {
    width: '48%',
    marginBottom: 15,
    backgroundColor: theme.colors.surface,
    borderRadius: 12,
    padding: 10,
    alignItems: 'center',
    ...theme.shadows.small,
    borderWidth: 1,
    borderColor: theme.colors.border,
    minHeight: 240,
  },
  wardrobeInventoryItemImage: {
    width: '100%',
    height: 100,
    borderRadius: 8,
    marginBottom: 6,
  },
  wardrobeInventoryItemInfo: {
    width: '100%',
    alignItems: 'center',
  },
  wardrobeInventoryItemTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    marginBottom: 5,
    textAlign: 'center',
    color: theme.colors.text,
  },
  wardrobeInventoryItemTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginBottom: 5,
  },
  wardrobeInventoryItemTag: {
    backgroundColor: theme.colors.border,
    borderRadius: 4,
    padding: 2,
    margin: 1,
  },
  wardrobeInventoryItemTagText: {
    fontSize: 8,
    color: theme.colors.textSecondary,
  },
  wardrobeInventoryItemActions: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 10,
  },
  editItemButton: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 25,
    backgroundColor: theme.colors.primary,
    ...theme.shadows.small,
  },
  editItemButtonText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: 'white',
  },
  deleteItemButton: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 25,
    backgroundColor: theme.colors.error,
    ...theme.shadows.small,
  },
  deleteItemButtonText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: 'white',
  },
  editItemModalContent: {
    width: '95%',
    backgroundColor: theme.colors.background,
    padding: 15,
    borderRadius: 10,
    height: '90%',
    flexDirection: 'column',
  },
  editItemModalScroll: {
    flex: 1,
    marginBottom: 10,
    paddingHorizontal: 5,
  },
  editItemImage: {
    width: '100%',
    height: 150,
    borderRadius: 8,
    marginBottom: 15,
  },
  editItemModalActions: {
    flexDirection: 'column',
    alignItems: 'center',
    gap: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: theme.colors.border,
  },
  editItemForm: {
    marginBottom: 15,
  },
  editItemField: {
    marginBottom: 15,
  },
  categoryDisplay: {
    backgroundColor: theme.colors.success + '20',
    borderRadius: 4,
    padding: 4,
    marginBottom: 5,
  },
  categoryDisplayText: {
    fontSize: 10,
    color: theme.colors.success,
    fontWeight: 'bold',
  },
  deleteEditButton: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 25,
    backgroundColor: theme.colors.error,
    ...theme.shadows.small,
  },
  deleteEditButtonText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: 'white',
  },
  editItemLabel: {
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 5,
    color: theme.colors.textSecondary,
  },
  editItemInput: {
    borderColor: theme.colors.border,
    borderWidth: 1,
    borderRadius: 8,
    padding: 10,
    marginBottom: 12,
    width: '100%',
    fontSize: 14,
    backgroundColor: theme.colors.surface,
    color: theme.colors.text,
  },
  editItemTagsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 12,
  },
  editItemTag: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 10,
    marginBottom: 5,
  },
  editItemTagText: {
    fontSize: 12,
    color: theme.colors.textSecondary,
  },
  removeTagButton: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 4,
    backgroundColor: theme.colors.error,
    marginLeft: 5,
  },
  removeTagButtonText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: 'white',
  },
  addTagContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  addTagInput: {
    flex: 1,
    borderColor: theme.colors.border,
    borderWidth: 1,
    borderRadius: 8,
    padding: 6,
    marginRight: 10,
    backgroundColor: theme.colors.surface,
    color: theme.colors.text,
  },
  addTagButton: {
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: theme.colors.primary,
    ...theme.shadows.small,
  },
  addTagButtonText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: 'white',
  },
  saveEditButton: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 25,
    backgroundColor: theme.colors.primary,
    ...theme.shadows.small,
  },
  saveEditButtonText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: 'white',
  },
  cancelEditButton: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 25,
    backgroundColor: theme.colors.textMuted,
    ...theme.shadows.small,
  },
  cancelEditButtonText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: theme.colors.textSecondary,
  },
  editItemModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 15,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
  },
  editItemModalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: theme.colors.text,
  },
  closeEditButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme.colors.surface,
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeEditButtonText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: theme.colors.textSecondary,
  },
  editIndicator: {
    backgroundColor: theme.colors.primary,
    borderRadius: 4,
    padding: 4,
    marginTop: 5,
  },
  editIndicatorText: {
    fontSize: 10,
    color: 'white',
    fontWeight: 'bold',
  },
  clearAllButton: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 25,
    backgroundColor: theme.colors.textMuted,
    ...theme.shadows.small,
  },
  clearAllButtonText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: theme.colors.textSecondary,
  },
  clearAllButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  clearAllIcon: {
    width: 20,
    height: 20,
    marginRight: 8,
  },
  clearAllImageButton: {
    width: 200,
    height: 80,
    borderRadius: 16,
    ...theme.shadows.medium,
  },
  outfitSuggestionsButton: {
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: theme.colors.primary,
    ...theme.shadows.small,
    marginTop: 6,
    marginBottom: 3,
  },
  outfitSuggestionsButtonText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: 'white',
  },
  slotOutfitSuggestionsButton: {
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: theme.colors.primary,
    ...theme.shadows.small,
    marginTop: 8,
    marginBottom: 5,
  },
  slotOutfitSuggestionsButtonText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: 'white',
  },
  navigationArrow: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: theme.colors.primary,
    ...theme.shadows.small,
    alignItems: 'center',
  },
  navigationArrowText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: 'white',
  },
  navigationArrowDisabled: {
    backgroundColor: theme.colors.textMuted,
  },
  outfitInfoContainer: {
    marginTop: 15,
    padding: 15,
    backgroundColor: theme.colors.surface,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  styleDNAInfo: {
    backgroundColor: theme.colors.success + '20',
    padding: 8,
    borderRadius: 8,
    marginBottom: 10,
  },
  styleDNAText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: theme.colors.success,
  },
  genderInfo: {
    backgroundColor: theme.colors.success + '20',
    padding: 8,
    borderRadius: 8,
    marginBottom: 10,
  },
  genderText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: theme.colors.success,
  },
  outfitDateText: {
    fontSize: 10,
    color: theme.colors.textSecondary,
    fontStyle: 'italic',
  },
  outfitItemsText: {
    fontSize: 10,
    color: theme.colors.textSecondary,
    fontWeight: 'bold',
  },
  downloadButton: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 25,
    backgroundColor: theme.colors.primary,
    ...theme.shadows.small,
    marginTop: 10,
  },
  downloadButtonText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: 'white',
  },
  removeLovedButton: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 25,
    backgroundColor: theme.colors.error,
    ...theme.shadows.small,
    marginTop: 10,
  },
  removeLovedButtonText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: 'white',
  },
  closeLovedButton: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 25,
    backgroundColor: theme.colors.textMuted,
    ...theme.shadows.small,
    alignItems: 'center',
  },
  closeLovedButtonText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: theme.colors.textSecondary,
  },
  sortFilterButton: {
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: theme.colors.primary,
    ...theme.shadows.small,
    alignItems: 'center',
  },
  sortFilterButtonText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: 'white',
  },
  currentFilterContainer: {
    backgroundColor: theme.colors.success + '20',
    padding: 8,
    borderRadius: 8,
    marginBottom: 10,
  },
  currentFilterText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: theme.colors.success,
    textAlign: 'center',
  },
  sortSection: {
    marginBottom: 15,
  },
  sortSectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: theme.colors.text,
  },
  sortOptionsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  sortOptionButton: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: theme.colors.surface,
    ...theme.shadows.small,
    marginRight: 5,
  },
  sortOptionButtonActive: {
    backgroundColor: theme.colors.primary,
  },
  sortOptionButtonText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: theme.colors.text,
  },
  sortOptionButtonTextActive: {
    color: 'white',
  },
  sortOrderSection: {
    marginBottom: 15,
  },
  sortOrderContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  sortOrderButton: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: theme.colors.surface,
    ...theme.shadows.small,
    marginRight: 5,
  },
  sortOrderButtonActive: {
    backgroundColor: theme.colors.primary,
  },
  sortOrderButtonText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: theme.colors.text,
  },
  sortOrderButtonTextActive: {
    color: 'white',
  },
  filterSection: {
    marginBottom: 15,
  },
  filterOptionsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  filterOptionButton: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: theme.colors.surface,
    ...theme.shadows.small,
    marginRight: 5,
  },
  filterOptionButtonActive: {
    backgroundColor: theme.colors.primary,
  },
  filterOptionButtonText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: theme.colors.text,
  },
  filterOptionButtonTextActive: {
    color: 'white',
  },
  resultsPreviewSection: {
    marginBottom: 15,
  },
  resultsPreviewContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  resultsPreviewText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: theme.colors.success,
  },
  resultsPreviewSubtext: {
    fontSize: 10,
    color: theme.colors.textSecondary,
  },
  resetButton: {
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: theme.colors.textMuted,
    ...theme.shadows.small,
    marginRight: 5,
  },
  resetButtonText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: theme.colors.textSecondary,
  },
  applyButton: {
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: theme.colors.primary,
    ...theme.shadows.small,
  },
  applyButtonText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: 'white',
  },
  closeSortFilterButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme.colors.surface,
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeSortFilterButtonText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: theme.colors.textSecondary,
  },
  sortFilterModalScroll: {
    maxHeight: '70%',
    marginBottom: 15,
  },
  sortFilterModalContent: {
    width: '90%',
    backgroundColor: theme.colors.background,
    padding: 20,
    borderRadius: 10,
    maxHeight: '80%',
  },
  sortFilterModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 15,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
  },
  sortFilterModalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: theme.colors.text,
  },
  sortFilterModalActions: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 10,
  },
  wardrobeItemInfoContainer: {
    marginTop: 15,
    padding: 15,
    backgroundColor: theme.colors.surface,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  wardrobeItemTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 5,
    color: theme.colors.text,
  },
  wardrobeItemDescription: {
    fontSize: 12,
    color: theme.colors.textSecondary,
  },
  wardrobeItemDetails: {
    marginBottom: 10,
  },
  wardrobeItemDetail: {
    fontSize: 12,
    color: theme.colors.textSecondary,
    marginBottom: 3,
  },
  wardrobeItemDetailLabel: {
    fontSize: 10,
    fontWeight: 'bold',
    color: theme.colors.success,
  },
  wardrobeItemTag: {
    backgroundColor: theme.colors.border,
    borderRadius: 4,
    padding: 4,
    margin: 2,
  },
  wardrobeItemTagText: {
    fontSize: 8,
    color: theme.colors.textSecondary,
  },
  wardrobeItemTags: {
    marginBottom: 5,
  },
  wardrobeItemTagsLabel: {
    fontSize: 10,
    fontWeight: 'bold',
    color: theme.colors.text,
  },
  wardrobeItemTagsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginBottom: 5,
  },
  wardrobeItemModalScroll: {
    flex: 1,
    marginBottom: 10,
    paddingHorizontal: 5,
  },
  wardrobeItemActionButtons: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 10,
  },
  wardrobeItemActionButton: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 25,
    backgroundColor: theme.colors.primary,
    ...theme.shadows.small,
  },
  wardrobeItemActionButtonText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: 'white',
  },
  bottomNavigation: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: theme.colors.background,
    borderTopWidth: 1,
    borderTopColor: theme.colors.border,
    ...theme.shadows.medium,
  },
  bottomNavButton: {
    flexDirection: 'column',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: 'transparent',
  },
  bottomNavIcon: {
    fontSize: 24,
    marginBottom: 4,
    color: theme.colors.textSecondary,
  },
  bottomNavIconActive: {
    color: theme.colors.primary,
  },
  bottomNavLabel: {
    fontSize: 10,
    fontWeight: '500',
    color: theme.colors.textSecondary,
  },
  bottomNavLabelActive: {
    color: theme.colors.primary,
    fontWeight: 'bold',
  },
  plusButton: {
    width: 56,
    height: 56,
    backgroundColor: theme.colors.primary,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
    ...theme.shadows.large,
  },
  plusButtonIcon: {
    fontSize: 32,
    fontWeight: 'bold',
    color: 'white',
  },
  profileButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.colors.surface,
    borderWidth: 2,
    borderColor: theme.colors.border,
    ...theme.shadows.small,
  },
  profileButtonImage: {
    width: 44,
    height: 44,
    borderRadius: 22,
  },
  profileButtonImageActive: {
    borderWidth: 3,
    borderColor: theme.colors.success,
  },
  profileButtonPlaceholder: {
    fontSize: 20,
    color: theme.colors.textSecondary,
  },
  genderSelectorModal: {
    width: '90%',
    backgroundColor: theme.colors.background,
    padding: 20,
    borderRadius: 15,
    ...theme.shadows.large,
  },
  genderSelectorHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 15,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
  },
  genderSelectorTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: 'bold',
    color: theme.colors.text,
  },
  closeGenderButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme.colors.surface,
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeGenderButtonText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: theme.colors.textSecondary,
  },
  genderSelectorSubtitle: {
    fontSize: 14,
    color: theme.colors.textSecondary,
    marginBottom: 20,
    textAlign: 'center',
  },
  genderOptionsContainer: {
    marginBottom: 20,
  },
  genderOption: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    marginBottom: 10,
    borderWidth: 2,
    borderColor: theme.colors.border,
    borderRadius: 12,
    backgroundColor: theme.colors.surface,
    ...theme.shadows.small,
  },
  genderOptionActive: {
    backgroundColor: theme.colors.success + '20',
    borderColor: theme.colors.success,
  },
  genderOptionIcon: {
    fontSize: 32,
    marginRight: 15,
  },
  genderOptionText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: theme.colors.text,
    marginBottom: 2,
  },
  genderOptionTextActive: {
    color: theme.colors.success,
  },
  genderOptionDescription: {
    fontSize: 12,
    color: theme.colors.textSecondary,
  },
  genderConfirmation: {
    padding: 12,
    borderRadius: 8,
    marginTop: 10,
  },
  genderConfirmationText: {
    fontSize: 12,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  bottomNavButtonWarning: {
    backgroundColor: theme.colors.error + '20',
    borderWidth: 1,
    borderColor: theme.colors.error,
  },
  bottomNavIconWarning: {
    color: theme.colors.textMuted,
  },
  bottomNavLabelWarning: {
    color: theme.colors.textMuted,
  },
  profilePageContainer: {
    flex: 1,
    backgroundColor: theme.colors.background,
    padding: 20,
    borderRadius: 10,
    marginTop: 20,
  },
  profilePageScroll: {
    flex: 1,
    marginBottom: 20,
  },
  profileHeader: {
    alignItems: 'center',
    marginBottom: 20,
  },
  profilePageTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: theme.colors.text,
  },
  profilePageSubtitle: {
    fontSize: 14,
    color: theme.colors.textSecondary,
    marginBottom: 10,
  },
  profileImageSection: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  profileImageContainer: {
    position: 'relative',
    marginRight: 20,
  },
  profilePageImage: {
    width: 100,
    height: 100,
    borderRadius: 8,
  },
  profileImagePlaceholder: {
    width: 100,
    height: 100,
    borderRadius: 8,
    backgroundColor: theme.colors.surface,
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileImagePlaceholderIcon: {
    fontSize: 32,
    color: theme.colors.textSecondary,
  },
  profileImagePlaceholderText: {
    fontSize: 12,
    color: theme.colors.textMuted,
    marginTop: 5,
  },
  profileImageEditButton: {
    position: 'absolute',
    top: 5,
    right: 5,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: theme.colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  profileImageEditIcon: {
    fontSize: 18,
    color: 'white',
  },
  analyzeButton: {
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: theme.colors.primary,
    ...theme.shadows.small,
    marginTop: 10,
  },
  analyzeButtonText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: 'white',
  },
  profileSection: {
    marginBottom: 20,
  },
  profileSectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: theme.colors.text,
    marginBottom: 5,
  },
  profileSectionSubtitle: {
    fontSize: 12,
    color: theme.colors.textSecondary,
  },
  dnaResultCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: 8,
    padding: 10,
    marginBottom: 10,
  },
  dnaResultTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: theme.colors.text,
    marginBottom: 5,
  },
  dnaResultContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  dnaResultItem: {
    fontSize: 12,
    color: theme.colors.textSecondary,
  },
  dnaResultLabel: {
    fontSize: 10,
    fontWeight: 'bold',
    color: theme.colors.success,
  },
  dnaResultDescription: {
    fontSize: 12,
    color: theme.colors.textSecondary,
    lineHeight: 16,
  },
  statsGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  statCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: 8,
    padding: 10,
    alignItems: 'center',
  },
  statNumber: {
    fontSize: 16,
    fontWeight: 'bold',
    color: theme.colors.text,
    marginBottom: 5,
  },
  statLabel: {
    fontSize: 12,
    color: theme.colors.textSecondary,
  },
  profileActions: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 10,
  },
  profileActionButton: {
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: theme.colors.primary,
    ...theme.shadows.small,
  },
  profileActionButtonText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: 'white',
  },
  genderSelectionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    borderWidth: 2,
    borderColor: theme.colors.border,
    borderRadius: 8,
    backgroundColor: theme.colors.surface,
    ...theme.shadows.small,
  },
  genderSelectionButtonWarning: {
    borderColor: theme.colors.error,
  },
  genderSelectionIcon: {
    fontSize: 24,
    marginRight: 10,
    color: theme.colors.textSecondary,
  },
  genderSelectionText: {
    fontSize: 14,
    color: theme.colors.textSecondary,
  },
  genderSelectionArrow: {
    fontSize: 16,
    color: theme.colors.textSecondary,
  },
  outfitsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  outfitCard: {
    width: '48%',
    marginBottom: 15,
    backgroundColor: theme.colors.card,
    borderRadius: 12,
    padding: 10,
    alignItems: 'center',
    ...theme.shadows.small,
    borderWidth: 1,
    borderColor: theme.colors.border,
    minHeight: 240,
  },
  lovedOutfitCard: {
    borderColor: theme.colors.error,
  },
  loveButton: {
    position: 'absolute',
    top: 5,
    right: 5,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: theme.colors.error,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  lovedButton: {
    backgroundColor: theme.colors.error,
  },
  loveButtonText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: 'white',
  },
  downloadOutfitButton: {
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: theme.colors.primary,
    ...theme.shadows.small,
    marginTop: 10,
  },
  downloadOutfitButtonText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: 'white',
  },
  outfitCardImage: {
    width: '100%',
    height: 150,
    borderRadius: 8,
    marginBottom: 6,
  },
  outfitCardInfo: {
    width: '100%',
    alignItems: 'center',
  },
  outfitWeatherBadge: {
    backgroundColor: theme.colors.success + '20',
    padding: 4,
    borderRadius: 6,
    marginBottom: 6,
  },
  outfitWeatherText: {
    fontSize: 10,
    color: theme.colors.success,
    fontWeight: 'bold',
  },
  outfitDNABadge: {
    backgroundColor: theme.colors.success + '20',
    padding: 4,
    borderRadius: 6,
    marginBottom: 6,
  },
  outfitDNAText: {
    fontSize: 10,
    color: theme.colors.success,
    fontWeight: 'bold',
  },
  generateFirstOutfitButton: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 25,
    backgroundColor: theme.colors.primary,
    ...theme.shadows.small,
    marginTop: 10,
  },
  generateFirstOutfitButtonText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: 'white',
  },
  // Category dropdown styles
  categoryDropdownButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.surface,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.colors.border,
    marginLeft: 8,
    minWidth: 100,
  },
  categoryDropdownText: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.colors.text,
    flex: 1,
  },
  categoryDropdownArrow: {
    fontSize: 12,
    color: theme.colors.textSecondary,
    marginLeft: 8,
  },
  categoryModalOverlay: {
    flex: 1,
    backgroundColor: theme.colors.modalBackdrop,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  categoryModalContent: {
    backgroundColor: theme.colors.background,
    borderRadius: 16,
    padding: 20,
    margin: 20,
    maxHeight: '80%',
    minWidth: 280,
    ...theme.shadows.large,
  },
  categoryModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
  },
  categoryModalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: theme.colors.text,
  },
  categoryModalScroll: {
    maxHeight: 300,
  },
  categoryOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: 12,
    marginVertical: 4,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  categoryOptionSelected: {
    backgroundColor: theme.colors.primary,
    borderColor: theme.colors.primary,
  },
  categoryOptionText: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.colors.text,
  },
  categoryOptionTextSelected: {
    color: 'white',
  },
  categoryCheckmark: {
    fontSize: 18,
    fontWeight: 'bold',
    color: 'white',
  },
  // Item detail view styles
  itemDetailContainer: {
    marginTop: 20,
    backgroundColor: theme.colors.background,
    borderRadius: 16,
    margin: 20,
    ...theme.shadows.medium,
  },
  itemDetailHeader: {
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
  },
  backButton: {
    alignSelf: 'flex-start',
    paddingVertical: 8,
    paddingHorizontal: 16,
    backgroundColor: theme.colors.surface,
    borderRadius: 20,
    marginBottom: 15,
  },
  backButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.colors.primary,
  },
  itemDetailTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: theme.colors.text,
    textAlign: 'center',
  },
  itemDetailImageContainer: {
    padding: 20,
    alignItems: 'center',
  },
  itemDetailImage: {
    width: '100%',
    height: 300,
    borderRadius: 12,
  },
  itemDetailInfo: {
    padding: 20,
  },
  itemDetailItemTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: theme.colors.text,
    marginBottom: 10,
  },
  itemDetailDescription: {
    fontSize: 16,
    color: theme.colors.textSecondary,
    lineHeight: 22,
    marginBottom: 20,
  },
  itemDetailField: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
    flexWrap: 'wrap',
  },
  itemDetailLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.colors.text,
    marginRight: 8,
    minWidth: 80,
  },
  itemDetailValue: {
    fontSize: 16,
    color: theme.colors.textSecondary,
    flex: 1,
  },
  itemDetailTagsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    flex: 1,
  },
  itemDetailTag: {
    backgroundColor: theme.colors.primary + '20',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    marginRight: 8,
    marginBottom: 4,
  },
  itemDetailTagText: {
    fontSize: 12,
    color: theme.colors.primary,
    fontWeight: '500',
  },
  itemDetailActions: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 30,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: theme.colors.border,
  },
  itemDetailActionButton: {
    backgroundColor: theme.colors.primary,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  itemDetailActionButtonText: {
    color: 'white',
    fontSize: 14,
    fontWeight: '600',
  },
  // Amazon suggestions styles
  amazonButton: {
    backgroundColor: theme.colors.warning,
  },
  disabledButton: {
    backgroundColor: theme.colors.textMuted,
    opacity: 0.6,
  },
  loadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  deleteActionButton: {
    backgroundColor: theme.colors.error,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    minWidth: 80,
    justifyContent: 'center',
  },
  deleteActionButtonText: {
    color: 'white',
    fontSize: 13,
    fontWeight: '600',
  },
  amazonSuggestionsSection: {
    marginTop: 30,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: theme.colors.border,
  },
  amazonSuggestionsHeader: {
    marginBottom: 16,
  },
  amazonHeaderContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  amazonHeaderText: {
    flex: 1,
    marginRight: 16,
  },
  amazonSuggestionsTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: theme.colors.text,
    marginBottom: 4,
  },
  amazonSuggestionsSubtitle: {
    fontSize: 14,
    color: theme.colors.textSecondary,
    marginBottom: 12,
  },
  refreshAmazonButton: {
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: theme.colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  refreshAmazonButtonText: {
    fontSize: 12,
    color: theme.colors.textSecondary,
    fontWeight: '600',
  },
  amazonSuggestionsScroll: {
    marginHorizontal: -20,
  },
  amazonSuggestionsContent: {
    paddingHorizontal: 20,
  },
  amazonSuggestionCard: {
    marginRight: 16,
    width: 180,
  },
  amazonPreviewContainer: {
    alignItems: 'center',
    minWidth: 80,
  },
  amazonPreviewLabel: {
    fontSize: 12,
    color: theme.colors.textSecondary,
    fontWeight: '600',
    marginBottom: 8,
    textAlign: 'center',
  },
  amazonPreviewImage: {
    width: 80,
    height: 80,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  // Editable field styles
  editableField: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.surface,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.colors.border,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flex: 1,
  },
  editIcon: {
    fontSize: 14,
    color: theme.colors.textSecondary,
    marginLeft: 8,
  },
  editFieldContainer: {
    flex: 1,
  },
  editFieldInput: {
    backgroundColor: theme.colors.background,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: theme.colors.primary,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 16,
    color: theme.colors.text,
  },
  // Tag editing styles
  editTagsContainer: {
    flex: 1,
  },
  tagsEditContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 10,
  },
  editableTag: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.primary + '20',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    marginRight: 8,
    marginBottom: 4,
  },
  editableTagText: {
    fontSize: 12,
    color: theme.colors.primary,
    fontWeight: '500',
  },
  removeTagText: {
    fontSize: 14,
    color: theme.colors.textSecondary,
    fontWeight: 'bold',
  },
  saveTagsButton: {
    backgroundColor: theme.colors.primary,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
  },
  saveTagsText: {
    color: 'white',
    fontSize: 12,
    fontWeight: '600',
  },
  // Outfit detail view styles
  outfitItemsSection: {
    marginTop: 20,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: theme.colors.border,
  },
  outfitItemsSectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: theme.colors.text,
    marginBottom: 15,
  },
  outfitItemsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  outfitItemCard: {
    width: '48%',
    backgroundColor: theme.colors.surface,
    borderRadius: 12,
    padding: 10,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  outfitItemImage: {
    width: '100%',
    height: 120,
    borderRadius: 8,
    marginBottom: 8,
  },
  outfitItemInfo: {
    alignItems: 'center',
  },
  outfitItemTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: theme.colors.text,
    textAlign: 'center',
    marginBottom: 4,
  },
  outfitItemCategory: {
    fontSize: 10,
    color: theme.colors.textSecondary,
    backgroundColor: theme.colors.primary + '20',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
    overflow: 'hidden',
  },
  // Laundry Management Styles
  laundrySection: {
    marginTop: 20,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: theme.colors.border,
  },
  laundrySectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  laundrySectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: theme.colors.text,
  },
  currentLaundryStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
  },
  currentLaundryStatusEmoji: {
    fontSize: 14,
    marginRight: 6,
  },
  currentLaundryStatusText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: 'white',
  },
  laundryControls: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 15,
  },
  laundryControlButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.border,
    opacity: 0.7,
  },
  laundryControlEmoji: {
    fontSize: 12,
    marginRight: 6,
  },
  laundryControlText: {
    fontSize: 11,
    color: theme.colors.textSecondary,
    fontWeight: '500',
  },
  laundryHistory: {
    backgroundColor: theme.colors.surface,
    padding: 12,
    borderRadius: 8,
    marginTop: 10,
  },
  laundryHistoryText: {
    fontSize: 12,
    color: theme.colors.textSecondary,
    textAlign: 'center',
  },
  
  // Photo source selection modal styles
  photoSourceModalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.colors.modalBackdrop,
  },
  photoSourceModalContent: {
    backgroundColor: theme.colors.background,
    borderRadius: 16,
    padding: 24,
    margin: 20,
    width: '90%',
    maxWidth: 400,
  },
  photoSourceModalTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: theme.colors.text,
    textAlign: 'center',
    marginBottom: 8,
  },
  photoSourceModalSubtitle: {
    fontSize: 16,
    color: theme.colors.textSecondary,
    textAlign: 'center',
    marginBottom: 24,
  },
  photoSourceOption: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderRadius: 12,
    backgroundColor: theme.colors.surface,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  photoSourceOptionIcon: {
    fontSize: 32,
    marginRight: 16,
  },
  photoSourceOptionText: {
    flex: 1,
  },
  photoSourceOptionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: theme.colors.text,
    marginBottom: 4,
  },
  photoSourceOptionSubtitle: {
    fontSize: 14,
    color: theme.colors.textSecondary,
  },
  photoSourceCancelButton: {
    marginTop: 16,
    padding: 16,
    borderRadius: 12,
    backgroundColor: theme.colors.surface,
    alignItems: 'center',
  },
  photoSourceCancelText: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.colors.textSecondary,
  },
  
  // Full screen overlay for camera and photo editing
  fullScreenOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1000,
    backgroundColor: theme.colors.overlay,
  },
  
  // AI Loading Overlay Styles
  aiLoadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: theme.colors.loadingOverlay,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
    borderRadius: 12,
  },
  aiLoadingCard: {
    backgroundColor: theme.colors.loadingCard,
    borderRadius: 16,
    padding: 30,
    alignItems: 'center',
    ...theme.shadows.large,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  aiLoadingTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: theme.colors.text,
    marginTop: 15,
    textAlign: 'center',
  },
  aiLoadingSubtext: {
    fontSize: 14,
    color: theme.colors.textSecondary,
    marginTop: 8,
    textAlign: 'center',
  },
  loadingProgress: {
    marginTop: 20,
    alignItems: 'center',
  },
  loadingStep: {
    fontSize: 12,
    color: theme.colors.textMuted,
    marginTop: 4,
    textAlign: 'center',
  },
  
  // Header Loading Styles - Enhanced and More Visible
  headerLoadingContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 999, // Below modal overlays but above content
    backgroundColor: theme.colors.primary,
    paddingTop: 50, // Account for status bar
    paddingBottom: 12, // Increased padding for more height
    paddingHorizontal: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5, // Android shadow
  },
  headerLoadingContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerLoadingText: {
    color: 'white',
    fontSize: 16, // Larger text - was 14
    fontWeight: '600', // Bolder text - was 500
    marginRight: 12,
    letterSpacing: 0.5, // Better letter spacing
  },
  headerLoadingSpinner: {
    fontSize: 20, // Larger spinner - was 16
    color: 'white',
  },
  
  // Random Outfit Generator Styles
  randomOutfitSection: {
    backgroundColor: theme.colors.card,
    borderRadius: 16,
    padding: 12,
    marginHorizontal: 16,
    marginVertical: 8,
    alignItems: 'center',
    ...theme.shadows.small,
  },
  randomOutfitTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: theme.colors.text,
    textAlign: 'center',
    marginBottom: 8,
  },
  randomOutfitSubtitle: {
    fontSize: 14,
    color: theme.colors.textSecondary,
    textAlign: 'center',
    marginBottom: 20,
    lineHeight: 20,
  },
  randomOutfitButtonContainer: {
    marginBottom: 8,
  },
  randomOutfitWarning: {
    fontSize: 12,
    color: theme.colors.warning || '#FF9500',
    textAlign: 'center',
    fontStyle: 'italic',
    marginTop: 8,
  },
  generationStatsContainer: {
    marginTop: 8,
    padding: 10,
    backgroundColor: theme.colors.surface,
    borderRadius: 12,
    width: '100%',
  },
  generationStatsTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    color: theme.colors.text,
    marginBottom: 4,
  },
  generationStats: {
    fontSize: 11,
    color: theme.colors.textSecondary,
    textAlign: 'center',
  },
  colorHarmonyIndicator: {
    fontSize: 10,
    color: theme.colors.success || '#4CAF50',
    textAlign: 'center',
    marginTop: 4,
    fontStyle: 'italic',
  },
  
  // Weather Context Styles
  weatherContextBanner: {
    backgroundColor: theme.colors.surface || theme.colors.background,
    borderRadius: 12,
    padding: 12,
    marginHorizontal: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: theme.colors.border,
    alignItems: 'center',
  },
  weatherText: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.colors.text,
    textAlign: 'center',
  },
  weatherDescription: {
    fontSize: 12,
    color: theme.colors.textSecondary,
    textAlign: 'center',
    marginTop: 4,
    fontStyle: 'italic',
  },
});